<a href="https://colab.research.google.com/github/keerthiamrish/NumPy-Arrays-Operations/blob/main/NumPy_Arrays_%26_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy Arrays & Operations**

 NumPy Arrays & Operations


In [1]:
import numpy as np

# 1D Array
arr1 = np.array([10, 20, 30, 40])

# 2D Array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

# 3D Array
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("1D Array:\n", arr1)
print("\n2D Array:\n", arr2)
print("\n3D Array:\n", arr3)

# Operations
print("\nAddition:", arr1 + 5)
print("Subtraction:", arr1 - 5)
print("Multiplication:", arr1 * 2)
print("Division:", arr1 / 2)

# Functions
print("\nMean:", np.mean(arr1))
print("Sum:", np.sum(arr1))
print("Standard Deviation:", np.std(arr1))

# Reshape
reshaped = arr1.reshape(2, 2)
print("\nReshaped Array:\n", reshaped)

# arange and linspace
print("\nArange:", np.arange(0, 10, 2))
print("Linspace:", np.linspace(0, 1, 5))

# Max and Min indices
print("\nIndex of Max:", np.argmax(arr1))
print("Index of Min:", np.argmin(arr1))

1D Array:
 [10 20 30 40]

2D Array:
 [[1 2 3]
 [4 5 6]]

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Addition: [15 25 35 45]
Subtraction: [ 5 15 25 35]
Multiplication: [20 40 60 80]
Division: [ 5. 10. 15. 20.]

Mean: 25.0
Sum: 100
Standard Deviation: 11.180339887498949

Reshaped Array:
 [[10 20]
 [30 40]]

Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]

Index of Max: 3
Index of Min: 0
